global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   static_map: true
   rolling_window: false
   track_unknown_space:  false
   resolution: 0.05
   transform_tolerance: 1.0
 
   plugins:
     - {name: static_layer,            type: "costmap_2d::StaticLayer"}
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
#     - {name: voxel_layer,          type: "costmap_2d::VoxelLayer"}
