local_costmap:
   global_frame: odom
   robot_base_frame: base_footprint
   static_map: false
   track_unknown_space: false
   rolling_window: true
   width: 10.0
   height: 10.0
   resolution: 0.025
   transform_tolerance: 1.0
   
   plugins:
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
#     - {name: voxel_layer,          type: "costmap_2d::VoxelLayer"}
     