# http://wiki.ros.org/navfn
NavfnROS:
    # Cost values taken from http://www.zkytony.com/documents/navguide.pdf
    lethal_cost:                        253   #default: 253
    neutral_cost:                       66    #default: 50
    cost_factor:                        0.55  #default: 3.0
    allow_unknown:                      true
    planner_window_x:                   0.0
    planner_window_y:                   0.0
    default_tolerance:                  0.0
    visualize_potential:                false

