#
# http://www.ros.org/wiki/amcl
# The first commented value is the default per the wiki
# The second commented value is the default per nav/amcl/examples
# The third commented value is the defaults in amcl_node.cpp
#
# The map file is specified in launch/amcl.launch

odom_frame_id:    odom
base_frame_id:    base_link
global_frame_id:  map
  
# Overall filter parameters
min_particles:        100       #default 100
max_particles:        1000      #default 5000
kld_err:              0.01      #default 0.05
kld_z:                0.99      #default 0.99
update_min_d:         0.025     #default 0.2
update_min_a:         0.05      #default pi/6 (0.5235)
resample_interval:    2         #default 1
transform_tolerance:  0.1       #default 0.1
recovery_alpha_slow:  0.001     #default 0.001
recovery_alpha_fast:  0.1       #default 0.01
#initial_pose_x:       21.273    #default 0.0
#initial_pose_y:       -2.702    #default 0.0
#initial_pose_a:       3.051     #default 0.0
gui_publish_rate:     -1.0      #default -1.0

# Laser Model Parameters 
laser_min_range:            0.1    #default -1.0
laser_max_range:            18.0   #default -1.0
laser_max_beams:            100    #default 30
laser_z_hit:                0.95   #default 0.95
laser_z_short:              0.1    #default 0.1
laser_z_max:                0.05   #default 0.05
laser_z_rand:               0.05   #default 0.05
laser_sigma_hit:            0.7    #default 0.2  
laser_lambda_short:         0.1    #default 0.1
laser_likelihood_max_dist:  2.0    #default 2.0
#laser_model_type:          likelihood_field #default likelihood_field
laser_model_type:           beam #default beam_const

# Odometery model parameters
odom_model_type:  diff-corrected
odom_alpha1:      0.05    #default 0.2 rotational    drift caused by rotation
odom_alpha2:      0.05    #default 0.2 rotational    drift caused by translation
odom_alpha3:      0.05    #default 0.2 translational drift caused by translation
odom_alpha4:      0.05    #default 0.2 translational drift caused by rotation
odom_alpha5:      0.05    #default 0.2 Holonomic drive systems only