local_costmap:
   global_frame: odom
   static_map: false
   track_unknown_space: true
   rolling_window: true
   width: 5.0
   height: 5.0
   resolution: 0.05
   transform_tolerance: 1.0
   update_frequency: 2.0
   publish_frequency: 1.0
   footprint_padding: 0.01
   
   plugins:
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
     - {name: voxel_layer,             type: "costmap_2d::VoxelLayer"}
     