base_global_planner: navfn/NavfnROS
base_local_planner:  base_local_planner/TrajectoryPlannerROS

#base_global_planner: global_planner/GlobalPlanner
#base_local_planner:  dwa_local_planner/DWAPlannerROS

planner_frequency:    0.0  # 0.0 means plan only when new goal received or local planner reports blocked
controller_frequency: 3.0

planner_patience:           5.0     # default: 5.0
controller_patience:        3.0     # default: 15.0
recovery_behavior_enabled:  true    # default: true
clearing_rotation_allowed:  true    # default: true
shutdown_costmaps:          false   # default: false
oscillation_timeout:        10.0    # default: 0.0
oscillation_distance:       0.5     # default: 0.5
conservative_reset_dist:    0.1     # default: 3.0

recovery_behaviors: [
    {name: conservative_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: rotate_recovery1, type: rotate_recovery/RotateRecovery}, 
    {name: aggressive_reset, type: clear_costmap_recovery/ClearCostmapRecovery},
    {name: rotate_recovery2, type: rotate_recovery/RotateRecovery}
]
  
conservative_clear: 
    reset_distance: 3.0
agressive_clear: 
    reset_distance: 1.875
rotate_recovery1:
    sim_granularity: 0.017
    frequency: 20.0
rotate_recovery2:
    sim_granularity: 0.017
    frequency: 20.0
    
