joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

head_pan_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_pan_joint
    pid: {p: 2.0, i: 0.5, d: 0.1}

head_tilt_position_controller:
    type: effort_controllers/JointPositionController
    joint: head_tilt_joint
    pid: {p: 2.0, i: 0.5, d: 0.1}
