# http://wiki.ros.org/global_planner
GlobalPlanner:
  lethal_cost:                  100   #default: 253
  neutral_cost:                 50    #default: 50
  cost_factor:                  3.0   #default: 3.0
  orientation_mode:             1     #default: 1-Forward
  publish_potential:            false #default: false

# http://wiki.ros.org/navfn
NavfnROS:
    allow_unknown:                      true
    planner_window_x:                   0.0
    planner_window_y:                   0.0
    default_tolerance:                  0.0
    visualize_potential:                false

# http://wiki.ros.org/base_local_planner
TrajectoryPlannerROS:
   max_vel_x: 0.2
   min_vel_x: 0.05
   max_vel_y: 0.0  # zero for a differential drive robot
   min_vel_y: 0.0
   max_vel_theta: 1.0
   min_vel_theta: -1.0
   min_in_place_vel_theta: 0.2
   escape_vel: 0.0 # Don't let the robot go backward
   acc_lim_x: 2.5
   acc_lim_y: 0.0  # zero for a differential drive robot
   acc_lim_theta: 3.2

   holonomic_robot: false
   yaw_goal_tolerance: 0.5  # about 25 degrees
   xy_goal_tolerance: 0.3  # 30 cm
   latch_xy_goal_tolerance: false
   pdist_scale: 0.8
   gdist_scale: 0.6
   occdist_scale: 0.05

   meter_scoring: true

   heading_lookahead: 0.5
   heading_scoring: false
   heading_scoring_timestep: 0.8
   oscillation_reset_dist: 0.05
   publish_cost_grid_pc: true
   prune_plan: true
   #escape_reset_theta: 1.1

   sim_time: 5.0
   sim_granularity: 0.025
   angular_sim_granularity: 0.025
   vx_samples: 6
   vy_samples: 0  # zero for a differential drive robot
   vtheta_samples: 10
   dwa: true
   simple_attractor: false
