#footprint: [[0.175, 0.175], [0.175, -0.175], [-0.175, -0.175], [-0.175, 0.175]]
#footprint_padding: 0.2

# NOTE: This is less than the actual radius so the robot will pass through narrow gaps.
robot_radius: 0.17

robot_base_frame: base_footprint

update_frequency: 5.0
transform_tolerance: 1.0

publish_frequency: 1.0
plugins: []

map_type: voxel

static:
  unknown_cost_value:        -1
  lethal_cost_threshold:     100
  map_topic:                 map
  subscribe_to_updates:      true
  enabled:                   true

simple_layer:
   conservative_reset_dist: 1.0
   enabled:              true
   unknown_threshold:    15
   mark_threshold:       0
   combination_method:   1
   track_unknown_space:  true    #true needed for disabling global path planning through unknown space
#   origin_z: 0.0
#   z_resolution: 0.2
#   z_voxels: 20
#   publish_voxel_map: true
  
#   observation_sources: base_scan
  
#   base_scan:
#      data_type:               LaserScan
#      topic:                   /scan
#      marking:                 true
#      clearing:                false
#      observation_persistence:  0.0
#      expected_update_rate:     5.0
#      inf_is_valid:             true
#      min_obstacle_height:      0.05
#      max_obstacle_height:      0.25
#      obstacle_range:           2.5
#      raytrace_range:           3.0

#voxel_layer:
#   unknown_threshold:    15
#   mark_threshold:       0
#   combination_method:   1
#   track_unknown_space:  true    #true needed for disabling global path planning through unknown space
#   origin_z: 0.0
#   z_resolution: 0.2
#   z_voxels: 20
#   publish_voxel_map: true
#
#   observation_sources: point_cloud_head_camera
#
#   point_cloud_head_camera:
#      data_type:                PointCloud2
#      topic:                    /camera/depth_registered/points
#      marking:                  true
#      clearing:                 true
#      observation_persistence:  0
#      min_obstacle_height:      -0.10
#      max_obstacle_height:      1.3
#      obstacle_range:           2.5
#      raytrace_range:           3.0
         
inflation_layer:
  enabled:              true
  cost_scaling_factor:  25.0  # exponential rate at which the obstacle cost drops off (default: 10)
  inflation_radius:     0.5  # max. distance from an obstacle at which costs are incurred for planning paths.
