global_costmap:
   global_frame: odom
   static_map: false
   rolling_window: true
   track_unknown_space:  true
   width: 10.0
   height: 10.0
   resolution: 0.05
   transform_tolerance: 1.0
   inflation_radius:     0.5
 
   plugins:
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: simple_layer,            type: "simple_layer_namespace::GridLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}
