local_costmap:
   global_frame: odom
   static_map: false
   track_unknown_space: false
   rolling_window: true
   width: 10.0
   height: 10.0
   resolution: 0.025
   transform_tolerance: 1.0
   
   plugins:
     - {name: obstacle_layer,          type: "costmap_2d::ObstacleLayer"}
     - {name: simple_layer,            type: "simple_layer_namespace::GridLayer"}
     - {name: inflation_layer,         type: "costmap_2d::InflationLayer"}