#footprint: [[0.17, 0.0], [0.0, 0.17], [0.0, -0.17], [-0.17, 0.0]]

cost_scaling_factor: 10
inflation_radius: 0.55

robot_radius: 0.17

footprint_padding: 0.1

map_type: costmap
resolution: 0.05

# The following parameters are only used if map_type is set to "costmap":
#track_unknown_space:    true

# The following parameters are only used if map_type is set to "voxel":
#origin_z:              0.0
#z_resolution:          0.2
#z_voxels:              10
#unknown_threshold:     5
#mark_threshold:        0

observation_sources: base_scan_points #point_cloud_head_camera

base_scan_points: {
  data_type:               LaserScan,
  #sensor_frame:            base_laser,
  #sensor_frame:            /camera_depth_frame,
  topic:                   /scan_filtered,
  marking:                 true,
  clearing:                true,
  #expected_update_rate:    0.5,
  observation_persistence: 0.0,
  inf_is_valid:            false,
  obstacle_range:          2.5,
  raytrace_range:          3.0,
  min_obstacle_height:     0.0,
  max_obstacle_height:     1.0
  }
  
point_cloud_head_camera: {
#   sensor_frame:            camera_rgb_optical_frame,
   data_type:               PointCloud2,
   topic:                   /camera/depth_registered/points,
   marking:                 true,
   clearing:                true,
   #expected_update_rate:    0.5,
   observation_persistence: 0.1,
   min_obstacle_height:     -0.10,
   max_obstacle_height:     1.5,
   obstacle_range:          2.5,
   raytrace_range:          3.0
   }
