# Planner selection
base_global_planner: "navfn/NavfnROS"
base_local_planner: "base_local_planner/TrajectoryPlannerROS"

# Oscillation
oscillation_timeout: 10.0
oscillation_distance: 0.2
conservative_reset_distance: 0.1

# Global planner
planner_frequency: 0.5
planner_patience: 5.0

# Local planner
controller_frequency: 10.0
controller_patience: 3.0

recovery_behavior_enabled: true
clearing_rotation_allowed: true
