#Independent settings for the planner's global costmap
global_costmap:
    global_frame:           map
    
    ### Map management parameters ### 
    static_map:             true  
    rolling_window:         false
    update_frequency:       1.0
    publish_frequency:      1.0
    unknown_cost_value:     0
    lethal_cost_threshold:  100
    publish_voxel_map:      true
    
    # The following parameters are overwritten if "static_map" is set to true:
    width:                  10.0
    height:                 10.0
    origin_x:               -5.0
    origin_y:               -5.0
    resolution:             0.05
