#Independent settings for the local costmap
local_costmap:
    global_frame:           odom
    
    ### Map management parameters ### 
    static_map:             false  
    rolling_window:         true
    update_frequency:       3.0
    publish_frequency:      2.0
    unknown_cost_value:     50
    lethal_cost_threshold:  100
    publish_voxel_map:      true
    
    # The following parameters are overwritten if "static_map" is set to true:
    width:                  10.0
    height:                 10.0
    origin_x:               -5.0
    origin_y:               -5.0
    resolution:             0.05
